/*
    JAVASCRIPT IS USED TO BUILD :
        WEBSITES---->REACTJS , ANGULARJS , VUEJS 
        APPLICATIONS(ANDROID OR APPLE)---->REACT NATIVE
        SERVERS---->EXPRESSJS , NODEJS
        WINDOWS---->ELECTRONJS
*/

// different data types ---> var , let , const

// YOU CAN SHOW OUTPUT OF JS ON EITHER ----------->CONSOLE , SCREEN OR PROMPT

/* 
    PRIMITIVE DATA TYPES
        NUMBER CHAR NULL UNDEFINED BOOLEAN 
        WE PASS THE VALUE 

    NON PRIMITIVE DATA TYPES    
        STRING OBJECTS ARRAYS
        WE PASS THE ADDRESS
*/